-- SQL used to create anything related to this webapp
CREATE TABLE PORTFOLIO_SITE.EXAMPLE_MESSAGES 
(
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(255), 
	words TEXT, 
	updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY(id)
);